### PR TITLE
decorators added

### PR DESCRIPTION
**Pull request by nrupeshsurya**
#28

### CODE REVIEW

**Comment by nrupeshsurya** [comment]
fixes #28

**Review by ChetanKhanna — COMMENTED** [review]
What about function based views? We need decorators there too I guess.

**Comment by nrupeshsurya** [comment]
function based views are being called from the class views?

**Comment by ChetanKhanna** [comment]
Can you check for all types of users that they can access only pages related to them?
Specially the data urls. So a student user should not be able to access get-hod-data/ url

**Comment by ChetanKhanna** [comment]
re-base and resolve conflicts.

**Pull request closed without merging**
