### PR TITLE
Fix #84 Added Export Feature

### LINKED ISSUE #84: Download database as xls
There is a particular format in which data is to be downloaded. Get the format from me and make a script for the same.

### PR DESCRIPTION
**Pull request by vezcraz**
url: /TMS/export
whomsoever has been approved by hod, they will be recorded in the files.

### CODE REVIEW

**Comment by ChetanKhanna** [comment]
We need it for all 5 sub types; 2 from PS2TS and 3 from TS2PS.

**Comment by ChetanKhanna** [comment]
squash these commits.

**Comment by vezcraz** [comment]
I did squash them. rebase -i HEAD-2 kiya tha

**Comment by vezcraz** [comment]
oh i made these changes directly on git. i'll make the necessary changes

**Pull request closed without merging**
